export const ggvMockQueueAbi = [
  {
    inputs: [
      { internalType: 'address', name: '__vault', type: 'address' },
      { internalType: 'address', name: '_steth', type: 'address' },
      { internalType: 'address', name: '_wsteth', type: 'address' },
      { internalType: 'address', name: '__owner', type: 'address' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  { anonymous: false, inputs: [], name: 'NonPure', type: 'event' },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'bytes32',
        name: 'requestId',
        type: 'bytes32',
      },
      { indexed: true, internalType: 'address', name: 'user', type: 'address' },
      {
        indexed: true,
        internalType: 'address',
        name: 'assetOut',
        type: 'address',
      },
      { indexed: false, internalType: 'uint96', name: 'nonce', type: 'uint96' },
      {
        indexed: false,
        internalType: 'uint128',
        name: 'amountOfShares',
        type: 'uint128',
      },
      {
        indexed: false,
        internalType: 'uint128',
        name: 'amountOfAssets',
        type: 'uint128',
      },
      {
        indexed: false,
        internalType: 'uint40',
        name: 'creationTime',
        type: 'uint40',
      },
      {
        indexed: false,
        internalType: 'uint24',
        name: 'secondsToMaturity',
        type: 'uint24',
      },
      {
        indexed: false,
        internalType: 'uint24',
        name: 'secondsToDeadline',
        type: 'uint24',
      },
    ],
    name: 'OnChainWithdrawRequested',
    type: 'event',
  },
  {
    inputs: [],
    name: '_owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: '_vault',
    outputs: [
      { internalType: 'contract GGVVaultMock', name: '', type: 'address' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'assetOut', type: 'address' }],
    name: '_withdrawAssets',
    outputs: [
      { internalType: 'bool', name: 'allowWithdraws', type: 'bool' },
      { internalType: 'uint24', name: 'secondsToMaturity', type: 'uint24' },
      {
        internalType: 'uint24',
        name: 'minimumSecondsToDeadline',
        type: 'uint24',
      },
      { internalType: 'uint16', name: 'minDiscount', type: 'uint16' },
      { internalType: 'uint16', name: 'maxDiscount', type: 'uint16' },
      { internalType: 'uint96', name: 'minimumShares', type: 'uint96' },
      { internalType: 'uint256', name: 'withdrawCapacity', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'accountant',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'authority',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'boringVault',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'uint96', name: 'nonce', type: 'uint96' },
          { internalType: 'address', name: 'user', type: 'address' },
          { internalType: 'address', name: 'assetOut', type: 'address' },
          { internalType: 'uint128', name: 'amountOfShares', type: 'uint128' },
          { internalType: 'uint128', name: 'amountOfAssets', type: 'uint128' },
          { internalType: 'uint40', name: 'creationTime', type: 'uint40' },
          { internalType: 'uint24', name: 'secondsToMaturity', type: 'uint24' },
          { internalType: 'uint24', name: 'secondsToDeadline', type: 'uint24' },
        ],
        internalType: 'struct IBoringOnChainQueue.OnChainWithdraw',
        name: 'request',
        type: 'tuple',
      },
    ],
    name: 'cancelOnChainWithdraw',
    outputs: [{ internalType: 'bytes32', name: 'requestId', type: 'bytes32' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'changeOwner',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getRequestIds',
    outputs: [{ internalType: 'bytes32[]', name: '', type: 'bytes32[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'requestId', type: 'bytes32' }],
    name: 'mockGetRequestById',
    outputs: [
      {
        components: [
          { internalType: 'uint96', name: 'nonce', type: 'uint96' },
          { internalType: 'address', name: 'user', type: 'address' },
          { internalType: 'address', name: 'assetOut', type: 'address' },
          { internalType: 'uint128', name: 'amountOfShares', type: 'uint128' },
          { internalType: 'uint128', name: 'amountOfAssets', type: 'uint128' },
          { internalType: 'uint40', name: 'creationTime', type: 'uint40' },
          { internalType: 'uint24', name: 'secondsToMaturity', type: 'uint24' },
          { internalType: 'uint24', name: 'secondsToDeadline', type: 'uint24' },
        ],
        internalType: 'struct IBoringOnChainQueue.OnChainWithdraw',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'nonce',
    outputs: [{ internalType: 'uint96', name: '', type: 'uint96' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'assetOut', type: 'address' },
      { internalType: 'uint128', name: 'amountOfShares', type: 'uint128' },
      { internalType: 'uint16', name: 'discount', type: 'uint16' },
    ],
    name: 'previewAssetsOut',
    outputs: [
      { internalType: 'uint128', name: 'amountOfAssets128', type: 'uint128' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'uint96', name: 'nonce', type: 'uint96' },
          { internalType: 'address', name: 'user', type: 'address' },
          { internalType: 'address', name: 'assetOut', type: 'address' },
          { internalType: 'uint128', name: 'amountOfShares', type: 'uint128' },
          { internalType: 'uint128', name: 'amountOfAssets', type: 'uint128' },
          { internalType: 'uint40', name: 'creationTime', type: 'uint40' },
          { internalType: 'uint24', name: 'secondsToMaturity', type: 'uint24' },
          { internalType: 'uint24', name: 'secondsToDeadline', type: 'uint24' },
        ],
        internalType: 'struct IBoringOnChainQueue.OnChainWithdraw',
        name: '',
        type: 'tuple',
      },
      { internalType: 'uint16', name: '', type: 'uint16' },
      { internalType: 'uint24', name: '', type: 'uint24' },
    ],
    name: 'replaceOnChainWithdraw',
    outputs: [
      { internalType: 'bytes32', name: '', type: 'bytes32' },
      { internalType: 'bytes32', name: '', type: 'bytes32' },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_assetOut', type: 'address' },
      { internalType: 'uint128', name: 'amountOfShares', type: 'uint128' },
      { internalType: 'uint16', name: 'discount', type: 'uint16' },
      { internalType: 'uint24', name: 'secondsToDeadline', type: 'uint24' },
    ],
    name: 'requestOnChainWithdraw',
    outputs: [{ internalType: 'bytes32', name: 'requestId', type: 'bytes32' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'assetOut', type: 'address' },
      { internalType: 'uint256', name: 'withdrawCapacity', type: 'uint256' },
    ],
    name: 'setWithdrawCapacity',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'uint96', name: 'nonce', type: 'uint96' },
          { internalType: 'address', name: 'user', type: 'address' },
          { internalType: 'address', name: 'assetOut', type: 'address' },
          { internalType: 'uint128', name: 'amountOfShares', type: 'uint128' },
          { internalType: 'uint128', name: 'amountOfAssets', type: 'uint128' },
          { internalType: 'uint40', name: 'creationTime', type: 'uint40' },
          { internalType: 'uint24', name: 'secondsToMaturity', type: 'uint24' },
          { internalType: 'uint24', name: 'secondsToDeadline', type: 'uint24' },
        ],
        internalType: 'struct IBoringOnChainQueue.OnChainWithdraw[]',
        name: 'requests',
        type: 'tuple[]',
      },
      { internalType: 'bytes', name: '', type: 'bytes' },
      { internalType: 'address', name: '', type: 'address' },
    ],
    name: 'solveOnChainWithdraws',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'steth',
    outputs: [{ internalType: 'contract IStETH', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'assetOut', type: 'address' },
      { internalType: 'uint24', name: 'secondsToMaturity', type: 'uint24' },
      {
        internalType: 'uint24',
        name: 'minimumSecondsToDeadline',
        type: 'uint24',
      },
      { internalType: 'uint16', name: 'minDiscount', type: 'uint16' },
      { internalType: 'uint16', name: 'maxDiscount', type: 'uint16' },
      { internalType: 'uint96', name: 'minimumShares', type: 'uint96' },
    ],
    name: 'updateWithdrawAsset',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'assetOut', type: 'address' }],
    name: 'withdrawAssets',
    outputs: [
      {
        components: [
          { internalType: 'bool', name: 'allowWithdraws', type: 'bool' },
          { internalType: 'uint24', name: 'secondsToMaturity', type: 'uint24' },
          {
            internalType: 'uint24',
            name: 'minimumSecondsToDeadline',
            type: 'uint24',
          },
          { internalType: 'uint16', name: 'minDiscount', type: 'uint16' },
          { internalType: 'uint16', name: 'maxDiscount', type: 'uint16' },
          { internalType: 'uint96', name: 'minimumShares', type: 'uint96' },
          {
            internalType: 'uint256',
            name: 'withdrawCapacity',
            type: 'uint256',
          },
        ],
        internalType: 'struct IBoringOnChainQueue.WithdrawAsset',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'wsteth',
    outputs: [{ internalType: 'contract IWstETH', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const;
